### ISSUE TITLE
[BUG] Static method findAndReplace leads to failure if the lineNo is 0 instead of null

### ISSUE THREAD

**Issue by michail-sygk** [st3v3nmw/obsidian-spaced-repetition#828]
**Describe the bug**
static method `findAndReplace` leads to failure if lineNo equals 0 instead of null.  

**To Reproduce**
1. Create a flashcard from line 0 which will call the method findAndReplace 
2. Example : 
```
---
Status:
  - 📁
  - ❓
family: 
links: 
moc:
---
# Chet Faker 
?
Chet Faker, whose real name is Nicholas James Murphy, is an Australian musician and singer-songwriter. He gained international recognition for his soulful and electronic music. Chet Faker's music often combines smooth vocals with innovative production, creating a distinct sound that resonates with a wide audience.
His breakout track, "No Diggity," a cover of the Blackstreet song, garnered widespread attention and marked the beginning of his successful career. Chet Faker has continued to evolve his style, exploring various genres and collaborating with other artists in the music industry.
![[Pasted image 20231208174523.png]]
https://www.youtube.com/watch?v=HIfFA8-RaHQ&ab_channel=njamesmurphy
```
3. Try to generate the flashcard

**Expected behavior**
The date metadata of the flashcard should be updated.

**Screenshots**
<img width="574" alt="image" src="https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/22731012/a302eca3-4f71-4560-a21e-87c07e4afb3f">

**Versions**

-   OS:  MAC
-   Obsidian version: v1.5.3
-   Plugin version:  v1.10.5

**Additional context**
Add any other context about the problem here (e.g. the markdown producing the error).

**Comment by ronzulu** [comment]
Hi @michail-sygk thanks for sending through the bug report.

This seems similar to #776  which has been fixed but not yet released.

There is a patched version available at: https://github.com/st3v3nmw/obsidian-spaced-repetition/issues/776#issuecomment-1831019886

Please try it out, and hopefully that will work for you. If not then the extra debug should give a clue.

Cheers
Ronny

**Comment by ronzulu** [comment]
Also, what version of the plug-in are you currently using? You wrote `v1.10.9`, but the latest is `v1.10.5`

**Comment by michail-sygk** [comment]
@ronzulu thanks or your quick response :)  
I updated the version to `v1.10.5`
unfortunately the patched version did not solve the issue. 
if you don't mind I would be really happy to try to help on this one. 
I could take a look during the weekend

**Comment by michail-sygk** [comment]
@ronzulu  
it did not solved the issue

I tried to debug it to find where is the issue. 

I attach some screenshots below that maybe will be useful. 
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/22731012/6cf7b6a1-5f55-49db-91e4-0f49b3ef00f0)

**Comment by ronzulu** [comment]
@michail-sygk, that's a great help.

Are you able to debug into:
![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/cdbf7deb-926e-42e6-8acc-1cac56262b28)

As you've noticed there is trailing space differences between `sourceTextArray` and `searchTextArray`.

This means that the (1) exact match test fails, and a more tolerant algorithm is used at (2)

So (3) should work regardless of leading/trailing space differences.

![image](https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/75528127/2cf898a9-8ba3-4a8e-99fa-5640a51603e9)

I don't know if I screwed up the logic within `MultiLineTextFinder.find` or if there is some system dependent reason why the comparison at (3) doesn't work. I say system dependent because I've never come across the issue personally.

If you are able to debug further, that would be great. Otherwise I'd include a version with heaps of debug within `find()` including hex dumps.

Cheers
Ronny

**Comment by michail-sygk** [comment]
Hey @ronzulu  

thanks for the detailed explanation and sorry for my late reply. However, I have some good news I think :) 

The issue arises when the `find` is called from line 1, which, from an index perspective, is actually 0. To illustrate this, consider the following scenario: even if I locate the index that should be 0, the subsequent check in the if (lineNo) statement essentially evaluates to nullish.

With screenshot I think everything will make sense : 
<img width="620" alt="image" src="https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/22731012/c729b245-3e7f-4ee4-a48b-462855da6f6b">

I tried as well this one and now everything looks like it's working perfectly fine. However I am not sure if I am missing something so I would like your opinion before opening a PR or you can fix it as well. 
<img width="648" alt="image" src="https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/22731012/270a9a9e-79d0-4a8d-900c-ee30dffa0318">

**Comment by ronzulu** [comment]
Hi @michail-sygk thanks for the detective work!

Happy for you to issue the PR given that you found and fixed the problem. You definitely should get the GitHub karma :-)

It's a little embarrassing as I'm relatively new to TypeScript and that's my second truthy bug. I'll definitely check the language spec before using it again!

Cheers
Ronny

**Comment by michail-sygk** [comment]
@ronzulu  heyy Ronny :) 
I opened a PR for the fix here and I updated as well the description of the issue 
https://github.com/st3v3nmw/obsidian-spaced-repetition/pull/830

**Comment by michail-sygk** [comment]
@ronzulu So I started reading recently the clean code and I fell on this interesting part that's is quietly related to our issue 
<img width="694" alt="image" src="https://github.com/st3v3nmw/obsidian-spaced-repetition/assets/22731012/e10af1e4-a9a4-4e13-862f-fa296b402e9e">
